## CHANGE this to the name of your plugin.
name: SpawnerPickaxePlugin

## CHANGE this to your username.
author: jnsbndgz

## CHANGE this to a meaningful but short description of your plugin.
description: A plugin that implements a spawner pickaxe.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.jnsbndgz.spawnerpickaxeplugin.SpawnerPickaxePlugin

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/jnsbndgz/spawner-pickaxe

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.18

## This is required and marks Slimefun as a plugin dependency.
depend:
- WildStacker

commands:
  spawnerpickaxe:
    description: This command can be used to retrive the Spawner Pickaxe
    usage: /spawnerpickaxe
    permission: spawnerpickaxe.givepickaxe